function T = gs1PCM(in1)
%gs1PCM
%    T = gs1PCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-Apr-2026 20:16:43

th1 = in1(:,1);
t2 = cos(th1);
t3 = sin(th1);
T = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0e+1,1.0],[4,4]);
end
