function T = gs3PCM(in1)
%gs3PCM
%    T = gs3PCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-Apr-2026 20:16:43

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
T = reshape([t2,t4,0.0,0.0,-t3.*t4,t2.*t3,t5,0.0,t4.*t5,-t2.*t5,t3,0.0,t3.*t4.*-5.0e+1+t4.*t5.*6.0e+1+t4.*t5.*th3,t2.*t3.*5.0e+1-t2.*t5.*6.0e+1-t2.*t5.*th3,t3.*6.0e+1+t5.*5.0e+1+t3.*th3+4.0e+1,1.0],[4,4]);
end
