function T = gs4PCM(in1)
%gs4PCM
%    T = gs4PCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-Apr-2026 20:16:43

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
th4 = in1(:,4);
t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th4);
t5 = sin(th1);
t6 = sin(th2);
t7 = sin(th4);
t8 = t4.*5.0e+1;
t9 = t8-5.0e+1;
T = reshape([t2.*t4-t3.*t5.*t7,t4.*t5+t2.*t3.*t7,t6.*t7,0.0,-t2.*t7-t3.*t4.*t5,-t5.*t7+t2.*t3.*t4,t4.*t6,0.0,t5.*t6,-t2.*t6,t3,0.0,t5.*t6.*6.0e+1-t3.*t4.*t5.*5.0e+1+t3.*t5.*t9+t5.*t6.*th3,t2.*t6.*-6.0e+1+t2.*t3.*t8-t2.*t3.*t9-t2.*t6.*th3,t3.*6.0e+1+t6.*t8-t6.*t9+t3.*th3+4.0e+1,1.0],[4,4]);
end
