function T = gs5PCM(in1)
%gs5PCM
%    T = gs5PCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-Apr-2026 20:16:43

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
th4 = in1(:,4);
th5 = in1(:,5);
t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th4);
t5 = cos(th5);
t6 = sin(th1);
t7 = sin(th2);
t8 = sin(th4);
t9 = sin(th5);
t10 = t2.*t8;
t11 = t6.*t8;
t12 = t4.*5.0e+1;
t13 = t5.*5.0e+1;
t14 = t9.*5.0e+1;
t16 = t5.*1.0e+2;
t17 = t9.*1.0e+2;
t18 = t2.*t3.*t4;
t19 = t3.*t4.*t6;
t15 = -t13;
t20 = t12-5.0e+1;
t21 = -t18;
t22 = t10+t19;
t25 = t14+t16-1.0e+2;
t23 = t11+t21;
t24 = t15+t17+5.0e+1;
mt1 = [t2.*t4-t3.*t11,t4.*t6+t3.*t10,t7.*t8,0.0,-t5.*t22+t6.*t7.*t9,-t5.*t23-t2.*t7.*t9,t3.*t9+t4.*t5.*t7,0.0,t9.*t22+t5.*t6.*t7,t9.*t23-t2.*t5.*t7,t3.*t5-t4.*t7.*t9,0.0,t10.*5.0e+1-t6.*t7.*4.0e+1-t5.*t22.*5.0e+1+t17.*t22-t22.*t24+t6.*t7.*t14+t3.*t6.*t20+t6.*t7.*t16-t6.*t7.*t25+t6.*t7.*th3,t11.*5.0e+1+t2.*t7.*4.0e+1-t5.*t23.*5.0e+1+t17.*t23-t23.*t24-t2.*t5.*t7.*1.0e+2-t2.*t7.*t9.*5.0e+1-t2.*t3.*t20+t2.*t7.*t25-t2.*t7.*th3];
mt2 = [t3.*-4.0e+1+t3.*t14+t3.*t16-t7.*t20-t3.*t25+t3.*th3-t4.*t7.*t9.*1.0e+2+t5.*t7.*t12+t4.*t7.*t24+4.0e+1,1.0];
T = reshape([mt1,mt2],4,4);
end
