function T = gstthPCM_ME(in1)
%gstthPCM_ME
%    T = gstthPCM_ME(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    15-Apr-2026 22:24:23

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = -th3;
t7 = t6+th2;
T = reshape([t2,t4,0.0,0.0,-t4,t2,0.0,0.0,0.0,0.0,1.0,0.0,t4.*-6.2e+1+t4.*t5.*7.5e+1-t3.*t4.*cos(th3).*8.0e+1-t4.*t5.*sin(th3).*8.0e+1+1.5e+2,t2.*(t5.*-7.5e+1+cos(t7).*8.0e+1+6.2e+1),t3.*7.5e+1+sin(t7).*8.0e+1+5.5e+1,1.0],[4,4]);
end
