function T = gstthPCM(in1)
%gstthPCM
%    T = gstthPCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-Apr-2026 20:16:43

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
th4 = in1(:,4);
th5 = in1(:,5);
th6 = in1(:,6);
t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th4);
t5 = cos(th5);
t6 = cos(th6);
t7 = sin(th1);
t8 = sin(th2);
t9 = sin(th4);
t10 = sin(th5);
t11 = sin(th6);
t12 = t2.*t4;
t13 = t3.*t5;
t14 = t2.*t9;
t15 = t4.*t7;
t16 = t7.*t9;
t17 = t4.*5.0e+1;
t18 = t5.*5.0e+1;
t19 = t10.*5.0e+1;
t21 = t5.*1.0e+2;
t22 = t6.*1.0e+2;
t23 = t10.*1.0e+2;
t25 = t5.*t7.*t8;
t26 = t4.*t8.*t10;
t30 = t2.*t5.*t8;
t20 = -t18;
t24 = t3.*t16;
t27 = t3.*t12;
t28 = t3.*t14;
t29 = t3.*t15;
t32 = -t26;
t33 = t17-5.0e+1;
t36 = t22-1.0e+2;
t44 = t19+t21-1.0e+2;
t31 = -t24;
t34 = -t27;
t37 = t14+t29;
t38 = t15+t28;
t41 = t13+t32;
t42 = t20+t23+5.0e+1;
t39 = t12+t31;
t40 = t16+t34;
t43 = t10.*t37;
t45 = t10.*t40;
t46 = t25+t43;
mt1 = [t11.*t39+t6.*t46,t11.*t38-t6.*(t30-t45),t6.*t41+t8.*t9.*t11,0.0,t6.*t39-t11.*t46,t6.*t38+t11.*(t30-t45),-t11.*t41+t6.*t8.*t9,0.0,-t5.*t37+t7.*t8.*t10,-t5.*t40-t2.*t8.*t10,t3.*t10+t4.*t5.*t8,0.0,t14.*5.0e+1-t7.*t8.*4.0e+1-t5.*t37.*8.0e+1+t22.*t46-t37.*t42-t36.*t46+t7.*t8.*t10.*8.0e+1+t3.*t7.*t33-t7.*t8.*t44+t7.*t8.*th3];
mt2 = [t16.*5.0e+1+t2.*t8.*4.0e+1-t5.*t40.*8.0e+1-t40.*t42-t22.*(t30-t45)+t36.*(t30-t45)-t2.*t8.*t10.*8.0e+1-t2.*t3.*t33+t2.*t8.*t44-t2.*t8.*th3,t3.*-4.0e+1+t3.*t10.*8.0e+1-t8.*t33-t3.*t44+t22.*t41-t36.*t41+t3.*th3+t4.*t5.*t8.*8.0e+1+t4.*t8.*t42+4.0e+1,1.0];
T = reshape([mt1,mt2],4,4);
end
