function T = gstthPCM(in1)
%gstthPCM
%    T = gstthPCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 18:10:40

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
th4 = in1(:,4);
th5 = in1(:,5);
th6 = in1(:,6);
t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th4);
t5 = cos(th5);
t6 = cos(th6);
t7 = sin(th1);
t8 = sin(th2);
t9 = sin(th4);
t10 = sin(th5);
t11 = sin(th6);
t12 = t2.*t4;
t13 = t3.*t5;
t14 = t2.*t9;
t15 = t4.*t7;
t16 = t7.*t9;
t18 = t5.*t7.*t8;
t19 = t4.*t8.*t10;
t23 = t2.*t5.*t8;
t17 = t3.*t16;
t20 = t3.*t12;
t21 = t3.*t14;
t22 = t3.*t15;
t25 = -t19;
t24 = -t17;
t26 = -t20;
t28 = t14+t22;
t29 = t15+t21;
t32 = t13+t25;
t30 = t12+t24;
t31 = t16+t26;
t33 = t10.*t28;
t34 = t10.*t31;
t35 = t18+t33;
T = reshape([t6.*t35+t11.*t30,t11.*t29-t6.*(t23-t34),t6.*t32+t8.*t9.*t11,0.0,t6.*t30-t11.*t35,t6.*t29+t11.*(t23-t34),-t11.*t32+t6.*t8.*t9,0.0,-t5.*t28+t7.*t8.*t10,-t5.*t31-t2.*t8.*t10,t3.*t10+t4.*t5.*t8,0.0,t3.*t7.*-5.0e+1+t7.*t8.*6.0e+1-t5.*t14.*3.0e+1-t13.*t15.*3.0e+1+t7.*t8.*t10.*3.0e+1+t7.*t8.*th3,t2.*t3.*5.0e+1-t2.*t8.*6.0e+1-t5.*t16.*3.0e+1+t12.*t13.*3.0e+1-t2.*t8.*t10.*3.0e+1-t2.*t8.*th3,t3.*6.0e+1+t8.*5.0e+1+t3.*t10.*3.0e+1+t3.*th3+t4.*t5.*t8.*3.0e+1+4.0e+1,1.0],[4,4]);
end
