function Vsab = Vsab_PCM(th,thd,d0,d1,d2)
%Vsab_PCM
%    Vsab = Vsab_PCM(TH,THD,D0,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    02-Mar-2026 20:09:05

Vsab = [0.0;0.0;-d1.*thd;thd;0.0;0.0];
end
