function gs2_th = me_arm_gs2_mot(in1)
%ME_ARM_GS2_MOT
%    GS2_TH = ME_ARM_GS2_MOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = -th3;
t7 = t6+th2;
t8 = cos(t7);
t9 = sin(t7);
gs2_th = reshape([t2,-t4,0.0,0.0,t4.*t8,t2.*t8,-t9,0.0,t4.*t9,t2.*t9,t8,0.0,t4.*t5.*(2.0./2.5e+1)+(t3.*t4.*cos(th3))./2.5e+1+(t4.*t5.*sin(th3))./2.5e+1+7.0./5.0e+1,(t2.*(t5.*(4.0./2.5e+1)+t8.*(2.0./2.5e+1)))./2.0,t3.*(2.0./2.5e+1)-t9./2.5e+1+5.175e-2,1.0],[4,4]);
end
