function gst_th = me_arm_gst(in1)
%ME_ARM_GST
%    GST_TH = ME_ARM_GST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

thA = in1(:,1);
thB = in1(:,2);
thC = in1(:,3);
t2 = cos(thA);
t3 = cos(thB);
t4 = cos(thC);
t5 = sin(thA);
t6 = sin(thB);
t7 = sin(thC);
t8 = thB+thC;
t9 = cos(t8);
t10 = sin(t8);
gst_th = reshape([t2,t5,0.0,0.0,-t5,t2,0.0,0.0,0.0,0.0,1.0,0.0,t5.*t6.*(-2.0./2.5e+1)-t3.*t4.*t5.*(2.0./2.5e+1)+t5.*t6.*t7.*(2.0./2.5e+1)-t3.*t4.*t5.*t9.*(3.0./5.0e+1)-t3.*t5.*t7.*t10.*(3.0./5.0e+1)-t4.*t5.*t6.*t10.*(3.0./5.0e+1)+t5.*t6.*t7.*t9.*(3.0./5.0e+1)+7.0./5.0e+1,t2.*(t6.*(2.0./2.5e+1)+t9.*(2.0./2.5e+1)+3.0./5.0e+1),t3.*(2.0./2.5e+1)-t10.*(2.0./2.5e+1)+5.175e-2,1.0],[4,4]);
end
