function gst_th = me_arm_gst_mot(in1)
%ME_ARM_GST_MOT
%    GST_TH = ME_ARM_GST_MOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

th1 = in1(:,1);
th2 = in1(:,2);
th3 = in1(:,3);
t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th3);
t5 = sin(th1);
t6 = sin(th2);
t7 = sin(th3);
t8 = -th3;
t9 = t8+th2;
t10 = cos(t9);
t11 = sin(t9);
gst_th = reshape([t2,-t5,0.0,0.0,t5,t2,0.0,0.0,0.0,0.0,1.0,0.0,t5.*t6.*(2.0./2.5e+1)+t3.*t4.*t5.*(2.0./2.5e+1)+t5.*t6.*t7.*(2.0./2.5e+1)+t3.*t4.*t5.*t10.*(3.0./5.0e+1)-t3.*t5.*t7.*t11.*(3.0./5.0e+1)+t4.*t5.*t6.*t11.*(3.0./5.0e+1)+t5.*t6.*t7.*t10.*(3.0./5.0e+1)+7.0./5.0e+1,t2.*(t6.*(2.0./2.5e+1)+t10.*(2.0./2.5e+1)+3.0./5.0e+1),t3.*(2.0./2.5e+1)-t11.*(2.0./2.5e+1)+5.175e-2,1.0],[4,4]);
end
