function gs2_th = me_arm_gs2(in1)
%ME_ARM_GS2
%    GS2_TH = ME_ARM_GS2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

thA = in1(:,1);
thB = in1(:,2);
thC = in1(:,3);
t2 = cos(thA);
t3 = cos(thB);
t4 = sin(thA);
t5 = sin(thB);
t6 = thB+thC;
t7 = cos(t6);
t8 = sin(t6);
gs2_th = reshape([t2,t4,0.0,0.0,-t4.*t7,t2.*t7,-t8,0.0,-t4.*t8,t2.*t8,t7,0.0,t4.*t5.*(-2.0./2.5e+1)-(t3.*t4.*cos(thC))./2.5e+1+(t4.*t5.*sin(thC))./2.5e+1+7.0./5.0e+1,(t2.*(t5.*(4.0./2.5e+1)+t7.*(2.0./2.5e+1)))./2.0,t3.*(2.0./2.5e+1)-t8./2.5e+1+5.175e-2,1.0],[4,4]);
end
