function gs1_th = me_arm_gs1(in1)
%ME_ARM_GS1
%    GS1_TH = ME_ARM_GS1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

thA = in1(:,1);
thB = in1(:,2);
t2 = cos(thA);
t3 = cos(thB);
t4 = sin(thA);
t5 = sin(thB);
gs1_th = reshape([t2,t4,0.0,0.0,-t3.*t4,t2.*t3,-t5,0.0,-t4.*t5,t2.*t5,t3,0.0,t4.*t5.*(-1.0./2.5e+1)+7.0./5.0e+1,(t2.*t5)./2.5e+1,t3./2.5e+1+5.175e-2,1.0],[4,4]);
end
