function gs0_th = me_arm_gs0(in1)
%ME_ARM_GS0
%    GS0_TH = ME_ARM_GS0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Apr-2026 12:17:16

thA = in1(:,1);
t2 = cos(thA);
t3 = sin(thA);
gs0_th = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,7.0./5.0e+1,0.0,0.0,1.0],[4,4]);
end
