function ME_Arm_IK_Export(TH_abc)
%% ME 4640 – HW D  |  IK Trajectory → Arduino Header Export
%
%  This script is your Part 4 starting point.  It:
%    1.  Generates a Cartesian trajectory (replace the star example with
%        YOUR Part 2 trajectory function).
%    2.  Runs your IK solver on every waypoint.
%    3.  Maps IK angles (th_a, th_b, th_c) → motor angles (th1, th2, th3).
%    4.  Exports a C header file  "trajectory.h"  for the Arduino sketch.
%    5.  (Optional) Animates the result so you can visually verify before
%        uploading to hardware.
%
%  Motor-angle mapping  (from Robot_HWC_Soln.m, FK derivation):
%    th_a =  th1          →  th1 =  th_a
%    th_b =  th2          →  th2 =  th_b
%    th_c = -th3 - th2    →  th3 = -(th_c + th_b)
%    th_d =  th3          (gripper, not used in IK export)
%
%  Copy  trajectory.h  into the same folder as  HWD_IK_Trajectory.ino
%  before uploading to the Arduino.

% =========================================================================
%  MOTOR-ANGLE MAPPING  (th_a,th_b,th_c → th1,th2,th3, in DEGREES)
% =========================================================================

th1_deg =  rad2deg( -TH_abc(:,1) );                  % base
th2_deg =  rad2deg(  TH_abc(:,2) );                  % shoulder
th3_deg =  rad2deg( -(TH_abc(:,3) + TH_abc(:,2)) );  % elbow

TRAJ_deg = [th1_deg, th2_deg, th3_deg];   % N×3, home-relative degrees

% =========================================================================
%  EXPORT  trajectory.h
%  Copy this file into the same folder as HWD_IK_Trajectory.ino
% =========================================================================

header_file = 'trajectory.h';
export_trajectory_header(TRAJ_deg, header_file);

% =========================================================================
%  OPTIONAL: plot joint angles to sanity-check before running on hardware
% =========================================================================

figure('Name','Exported motor angles','Color','w')
N = length(TRAJ_deg);
t_vec = (0:N-1);
subplot(3,1,1); plot(t_vec, TRAJ_deg(:,1)); ylabel('\theta_1 (deg)'); title('Base');   grid on
subplot(3,1,2); plot(t_vec, TRAJ_deg(:,2)); ylabel('\theta_2 (deg)'); title('Shoulder'); grid on
subplot(3,1,3); plot(t_vec, TRAJ_deg(:,3)); ylabel('\theta_3 (deg)'); title('Elbow');    grid on
xlabel('Waypoint index')
sgtitle('Exported motor angles (verify before uploading)')

end 

% =========================================================================
%  LOCAL FUNCTION: export_trajectory_header
% =========================================================================

function export_trajectory_header(TRAJ, filename)
% export_trajectory_header  Write a C header file for the HWD Arduino sketch.
%
%   TRAJ     – N×3 matrix of [th1, th2, th3] in home-relative degrees
%   filename – output filename (e.g. 'trajectory.h')
%
%  The header stores the array in AVR program memory (PROGMEM) to keep it
%  out of the Arduino's limited 2 KB SRAM.  Flash usage:
%    N waypoints × 3 joints × 4 bytes = N×12 bytes
%  (200 waypoints ≈ 2.3 KB flash — well within the Uno's 32 KB limit)

    N = size(TRAJ, 1);
    fid = fopen(filename, 'w');
    if fid == -1
        error('Could not open "%s" for writing. Check the current folder.', filename);
    end

    fprintf(fid, '// trajectory.h  –  auto-generated by ME_Arm_IK_Export.m\n');
    fprintf(fid, '// DO NOT EDIT MANUALLY – regenerate from your MATLAB/Python IK script.\n');
    fprintf(fid, '//\n');
    fprintf(fid, '// Columns: { th1_deg, th2_deg, th3_deg }\n');
    fprintf(fid, '//   th1 = base     (home-relative, degrees)\n');
    fprintf(fid, '//   th2 = shoulder (home-relative, degrees)\n');
    fprintf(fid, '//   th3 = elbow    (home-relative, degrees)\n');
    fprintf(fid, '//\n');
    fprintf(fid, '// Mapping applied (from Robot_HWC_Soln.m):\n');
    fprintf(fid, '//   th1 =  th_a\n');
    fprintf(fid, '//   th2 =  th_b\n');
    fprintf(fid, '//   th3 = -(th_c + th_b)\n');
    fprintf(fid, '\n');
    fprintf(fid, '#pragma once\n');
    fprintf(fid, '#include <avr/pgmspace.h>\n');
    fprintf(fid, '\n');
    fprintf(fid, '#define N_WPT %d\n', N);
    fprintf(fid, '\n');
    fprintf(fid, 'const float TRAJ[N_WPT][3] PROGMEM = {\n');

    for k = 1:N
        comma = ',';
        if k == N, comma = ' '; end
        fprintf(fid, '  { %9.4f, %9.4f, %9.4f }%s\n', ...
            TRAJ(k,1), TRAJ(k,2), TRAJ(k,3), comma);
    end

    fprintf(fid, '};\n');
    fclose(fid);

    flash_kb = N * 3 * 4 / 1024;
    fprintf('\nExported  %s\n', filename);
    fprintf('  Waypoints : %d\n', N);
    fprintf('  Flash used: %.1f KB  (of 32 KB on Uno)\n', flash_kb);
    fprintf('\nNext step: copy trajectory.h into your HWD_IK_Trajectory sketch folder.\n');
end
