"""
ME 4640 – ME Arm V3.0 Forward Kinematics
==========================================
Provides FK transforms for each link using the product-of-exponentials (POE)
formula, following Murray et al. "A Mathematical Introduction to Robotic
Manipulation" (1994) — the same framework used throughout the course.

Equivalent to the MATLAB functions me_arm_gs0 / gs1 / gs2 / gst that are
generated by ME_Arm_FK_Animation_Example.m.

This module uses SE3 and SO3 from robotics_utils (course utilities) instead
of reimplementing the exponential map — keeping notation consistent with
lecture and homework.

Robot constants  (all in metres)
---------------------------------
  D0 = 0.140    base pivot X-offset from world origin
  D1 = 0.05175  shoulder pivot height above ground
  D2 = 0.080    upper arm length
  D3 = 0.080    forearm length
  D4 = 0.060    tool radial offset from wrist pivot

Joint definitions (world frame, robot at home)
----------------------------------------------
  Joint 1 – base     : w = [0, 0, 1],   q = [D0, 0,   0      ]
  Joint 2 – shoulder : w = [-1, 0, 0],  q = [D0, 0,   D1     ]
  Joint 3 – elbow    : w = [-1, 0, 0],  q = [D0, 0,   D1+D2  ]
  Joint 4 – wrist    : w = [-1, 0, 0],  q = [D0, D3,  D1+D2  ]
             th4 = -th2 - th3  (kinematic constraint, keeps tool horizontal)

Usage
-----
  from me_arm_fk import me_arm_gs0, me_arm_gs1, me_arm_gs2, me_arm_gst

  th = [th1, th2, th3]   # radians, home-relative motor angles
  T_tool = me_arm_gst(th)
  tip    = T_tool @ [0, 0, 0, 1]   # homogeneous tool-tip position (m)
"""

import numpy as np
import SE3      # course robotics_utils: SE3.twist(), SE3.expt()


# ── Robot constants (metres) ─────────────────────────────────────────────────
D0 = 0.140       # base X offset
D1 = 0.05175     # shoulder pivot height
D2 = 0.080       # upper arm
D3 = 0.080       # forearm
D4 = 0.060       # tool

# ── Joint axes (unit vectors) ─────────────────────────────────────────────────
_W1 = np.array([ 0.,  0.,  1.])   # base     – Z
_W2 = np.array([-1.,  0.,  0.])   # shoulder – -X
_W3 = np.array([-1.,  0.,  0.])   # elbow    – -X
_W4 = np.array([-1.,  0.,  0.])   # wrist    – -X

# ── Points on each rotation axis (home configuration, metres) ────────────────
_Q1 = np.array([D0,  0.,       0.    ])
_Q2 = np.array([D0,  0.,       D1    ])
_Q3 = np.array([D0,  0.,       D1+D2 ])
_Q4 = np.array([D0,  D3,       D1+D2 ])

# ── Twist coordinates: xi = SE3.twist(w, q) = [-w×q; w] ─────────────────────
_XI1 = SE3.twist(_W1, _Q1)
_XI2 = SE3.twist(_W2, _Q2)
_XI3 = SE3.twist(_W3, _Q3)
_XI4 = SE3.twist(_W4, _Q4)

# ── Home configuration transforms (identity rotation, pure translation) ──────
def _home(p):
    """4×4 identity-rotation transform with translation p."""
    T = np.eye(4)
    T[:3, 3] = p
    return T

_GS0_0 = _home([D0,     0.,         0.       ])   # base link centre
_GS1_0 = _home([D0,     0.,         D1+D2/2  ])   # shoulder link centre
_GS2_0 = _home([D0,     D3/2,       D1+D2    ])   # elbow link centre
_GST_0 = _home([D0,     D3+D4,      D1+D2    ])   # tool tip


# ── FK transforms ─────────────────────────────────────────────────────────────

def me_arm_gs0(th):
    """
    4×4 FK transform for the rotating base link.

    POE:  T = exp(xi1 * th1) * G0_home

    Parameters
    ----------
    th : array-like [th1, th2, th3]  (radians, home-relative)

    Returns
    -------
    T : (4,4) ndarray
    """
    E1 = SE3.expt(_XI1, th[0])
    return E1 @ _GS0_0


def me_arm_gs1(th):
    """
    4×4 FK transform for the shoulder (upper arm) link.

    POE:  T = exp(xi1*th1) * exp(xi2*th2) * G1_home
    """
    E1 = SE3.expt(_XI1, th[0])
    E2 = SE3.expt(_XI2, th[1])
    return E1 @ E2 @ _GS1_0


def me_arm_gs2(th):
    """
    4×4 FK transform for the elbow (forearm) link.

    POE:  T = exp(xi1*th1) * exp(xi2*th2) * exp(xi3*th3) * G2_home
    """
    E1 = SE3.expt(_XI1, th[0])
    E2 = SE3.expt(_XI2, th[1])
    E3 = SE3.expt(_XI3, th[2])
    return E1 @ E2 @ E3 @ _GS2_0


def me_arm_gst(th):
    """
    4×4 FK transform for the tool (end-effector) frame.

    POE:  T = exp(xi1*th1) * exp(xi2*th2) * exp(xi3*th3) * exp(xi4*th4) * Gst_home

    Kinematic constraint:  th4 = -th2 - th3
    (The wrist compensates for elbow and shoulder motion to keep the tool
    pointing horizontally — built into the ME Arm V3 linkage geometry.)
    """
    th4 = -th[1] - th[2]   # kinematic constraint
    E1  = SE3.expt(_XI1, th[0])
    E2  = SE3.expt(_XI2, th[1])
    E3  = SE3.expt(_XI3, th[2])
    E4  = SE3.expt(_XI4, th4)
    return E1 @ E2 @ E3 @ E4 @ _GST_0


# ── rectverts: box geometry helper ───────────────────────────────────────────

def rectverts(bounds, color):
    """
    Build a homogeneous vertex matrix and face-index array for a rectangular box.
    Equivalent to MATLAB's  rectverts()  in the functions/ folder.

    Parameters
    ----------
    bounds : [xmin, xmax, ymin, ymax, zmin, zmax]
    color  : [r, g, b]  (values 0–1)

    Returns
    -------
    HV : (4, 8) float ndarray   – homogeneous columns of the 8 box corners
    F  : (6, 4) int ndarray     – face indices  (each row = one quad face)
    C  : (3,)   float ndarray   – RGB colour

    Face ordering matches MATLAB rectverts:
      Face 0 – xz-plane at ymin   (front)
      Face 1 – yz-plane at xmax   (right)
      Face 2 – xz-plane at ymax   (back)
      Face 3 – yz-plane at xmin   (left)
      Face 4 – xy-plane at zmin   (bottom)
      Face 5 – xy-plane at zmax   (top)
    """
    xm, xM, ym, yM, zm, zM = bounds
    #       v0   v1   v2   v3   v4   v5   v6   v7
    HV = np.array([
        [xm,  xM,  xM,  xm,  xm,  xM,  xM,  xm],   # x
        [ym,  ym,  yM,  yM,  ym,  ym,  yM,  yM],    # y
        [zm,  zm,  zm,  zm,  zM,  zM,  zM,  zM],    # z
        [ 1,   1,   1,   1,   1,   1,   1,   1],    # w  (homogeneous)
    ], dtype=float)

    F = np.array([
        [0, 1, 5, 4],   # xz @ ymin
        [1, 2, 6, 5],   # yz @ xmax
        [2, 3, 7, 6],   # xz @ ymax
        [3, 0, 4, 7],   # yz @ xmin
        [0, 1, 2, 3],   # xy @ zmin
        [4, 5, 6, 7],   # xy @ zmax
    ], dtype=int)

    return HV, F, np.asarray(color, dtype=float)
