function gab_th = gabth_PCM(th,d0,d1,d2)
%gabth_PCM
%    GAB_TH = gabth_PCM(TH,D0,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    02-Mar-2026 20:09:05

t2 = cos(th);
t3 = sin(th);
gab_th = reshape([0.0,-t3,t2,0.0,1.0,0.0,0.0,0.0,0.0,t2,t3,0.0,d0,d1+d2.*t2,d2.*t3,1.0],[4,4]);
end
