% HW03_Martin_plotting.m
% Plots the y/z position and y/z velocity of the end-effector point r
% as the joint follows a sine-wave motion from 0 to 270 deg at 0.2 Hz.
%
% Requires: gabth_PCM.m and Vsab_PCM.m (generated by HW03_Martin_kinematics.m)
%
% Dimensions (inches):
%   d0 = 3.1,  d1 = 1.5,  d2 = 2.4,  d3 = 3.3

clear; clc; close all;
addpath('../Functions')

%% Numeric dimensions (inches)
d0 = 3.1;
d1 = 1.5;
d2 = 2.4;
d3 = 3.3;

rb = [d3; 0; 0; 1];    % end-effector in frame B coords (homogeneous)

%% Sine-wave joint trajectory
%   theta(t) = (270/2) * (1 - cos(2*pi*f*t))  [degrees]
%   Ranges 0 -> 270 deg, starts at 0, frequency f = 0.2 Hz, duration 10 s
f   = 0.2;                                      % Hz
t   = linspace(0, 10, 1000);                    % time vector (s)

th  = (3*pi/4) * (1 - cos(2*pi*f*t));           % joint angle (rad), 0 to 3pi/2
thd = (3*pi/4) * (2*pi*f) * sin(2*pi*f*t);      % joint velocity (rad/s)

%% Compute position and velocity of point r at each timestep
n     = length(t);
y_pos = zeros(1, n);   % y-position of r in frame A (in)
z_pos = zeros(1, n);   % z-position of r in frame A (in)
y_vel = zeros(1, n);   % y-velocity of r in frame A (in/s)
z_vel = zeros(1, n);   % z-velocity of r in frame A (in/s)

for i = 1:n
    % Forward kinematics: position of end-effector in frame A
    G  = gabth_PCM(th(i), d0, d1, d2);     % 4x4 HGT gab(th)
    ra = G * rb;                             % [x; y; z; 1] in frame A

    % Spatial velocity of frame B (6x1): Vsab = [v^s; omega^s]
    Vs = Vsab_PCM(th(i), thd(i), d0, d1, d2);
    vs = Vs(1:3);    % linear velocity component (spatial frame)
    ws = Vs(4:6);    % angular velocity component (spatial frame)

    % Velocity of point r on the body (spatial frame):
    %   r_dot = v^s + omega^s x r_a   (from V_hat^s * [r_a; 1])
    vel_r = vs + cross(ws, ra(1:3));

    y_pos(i) = ra(2);
    z_pos(i) = ra(3);
    y_vel(i) = vel_r(2);
    z_vel(i) = vel_r(3);
end

%% Plot
figure;
hold on;
grid on;

plot(t, y_pos, 'b', 'LineWidth', 2);
plot(t, z_pos, 'r', 'LineWidth', 2);
plot(t, y_vel, 'c', 'LineWidth', 2);
plot(t, z_vel, 'm', 'LineWidth', 2);

xlabel('Time (s)');
ylabel('inches  or  inches/sec');
title('End-Effector Point r — Position and Velocity vs. Time');
legend('y_{pos} (in)', 'z_{pos} (in)', 'y_{vel} (in/s)', 'z_{vel} (in/s)', ...
       'Location', 'best');

hold off;
