function ME_Arm_IK_Export_PCM(TH, filename)
% ME_Arm_IK_Export_PCM  Export an IK joint trajectory as trajectory.h.
%
%   ME_Arm_IK_Export_PCM(TH, filename)
%
%   Inputs:
%       TH       - N x 3 matrix of KINEMATIC joint angles [th1, th2, th3]
%                  in radians (as returned by ME_Arm_IK_PCM and accepted
%                  by gstthPCM_ME).
%       filename - output path for the generated header file (e.g.
%                  'trajectory.h').
%
%   Motor-angle mapping (from RobotC_Martin_Kinematics.m substitution):
%       kinematic -> FK twist convention:
%           theta_a =  th1,   theta_b =  th2,   theta_c = -th3
%       assignment-sheet motor mapping:
%           motor th1 = -theta_a            = -th1_kin
%           motor th2 =  theta_b            =  th2_kin
%           motor th3 = -(theta_c + theta_b)=  th3_kin - th2_kin
%
%   The output header stores the table in AVR PROGMEM so it lives in
%   flash rather than the Uno's 2 KB SRAM.  Flash usage ~= N * 12 bytes.

    if nargin < 2 || isempty(filename), filename = 'trajectory.h'; end

    % --- Apply motor-angle mapping (radians) then convert to degrees ----
    motor_th1 = -TH(:,1);
    motor_th2 =  TH(:,2);
    motor_th3 =  TH(:,3) - TH(:,2);
    TRAJ_deg  = rad2deg([motor_th1, motor_th2, motor_th3]);

    % --- Write the header file -----------------------------------------
    N   = size(TRAJ_deg, 1);
    fid = fopen(filename, 'w');
    if fid == -1
        error('Could not open "%s" for writing.', filename);
    end
    fprintf(fid, '// trajectory.h  -  auto-generated by ME_Arm_IK_Export_PCM.m\n');
    fprintf(fid, '// Author:  Paul C. Martin (PCM)   ME 4640 S26   HW D\n');
    fprintf(fid, '// DO NOT EDIT MANUALLY - regenerate via ME_Arm_Traj_PCM.m.\n');
    fprintf(fid, '//\n');
    fprintf(fid, '// Columns: { th1_deg, th2_deg, th3_deg }  (home-relative, degrees)\n');
    fprintf(fid, '// Motor mapping applied:\n');
    fprintf(fid, '//   motor_th1 = -theta_a         = -th1_kin\n');
    fprintf(fid, '//   motor_th2 =  theta_b         =  th2_kin\n');
    fprintf(fid, '//   motor_th3 = -(theta_c + th_b)=  th3_kin - th2_kin\n');
    fprintf(fid, '\n');
    fprintf(fid, '#pragma once\n');
    fprintf(fid, '#include <avr/pgmspace.h>\n\n');
    fprintf(fid, '#define N_WPT %d\n\n', N);
    fprintf(fid, 'const float TRAJ[N_WPT][3] PROGMEM = {\n');
    for k = 1:N
        comma = ','; if k == N, comma = ' '; end
        fprintf(fid, '  { %9.4f, %9.4f, %9.4f }%s\n', ...
                TRAJ_deg(k,1), TRAJ_deg(k,2), TRAJ_deg(k,3), comma);
    end
    fprintf(fid, '};\n');
    fclose(fid);

    flash_kb = N * 3 * 4 / 1024;
    fprintf('\nExported "%s"\n', filename);
    fprintf('  Waypoints : %d\n', N);
    fprintf('  Flash used: %.1f KB  (of 32 KB on the Uno)\n', flash_kb);
    fprintf('  Min/Max   : th1 [%7.2f, %7.2f] deg\n', ...
            min(TRAJ_deg(:,1)), max(TRAJ_deg(:,1)));
    fprintf('              th2 [%7.2f, %7.2f] deg\n', ...
            min(TRAJ_deg(:,2)), max(TRAJ_deg(:,2)));
    fprintf('              th3 [%7.2f, %7.2f] deg\n', ...
            min(TRAJ_deg(:,3)), max(TRAJ_deg(:,3)));

    % Quick plot so you can eyeball the shape before uploading
    figure('Name','Exported motor angles','Color','w')
    t_vec = 0:N-1;
    subplot(3,1,1); plot(t_vec, TRAJ_deg(:,1),'LineWidth',1.4);
        ylabel('\theta_1 (deg)'); title('Base');     grid on
    subplot(3,1,2); plot(t_vec, TRAJ_deg(:,2),'LineWidth',1.4);
        ylabel('\theta_2 (deg)'); title('Shoulder'); grid on
    subplot(3,1,3); plot(t_vec, TRAJ_deg(:,3),'LineWidth',1.4);
        ylabel('\theta_3 (deg)'); title('Elbow');    grid on
    xlabel('Waypoint index')
    sgtitle('trajectory.h motor angles  (verify before uploading)')
end
